version: '3'
services:
  mysql:
    container_name: mysql
    build: ./mysql/  # Dockerfileからビルドすることを示す
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d  # 初期データ
    environment:
      MYSQL_ROOT_PASSWORD: root # 環境変数
    ports:
      - "3306:3306"
  postgresql:
    container_name: postgres
    image: postgres
    volumes:
      - ./postgres/db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
  embulk:
    container_name: embulk
    build: ./embulk/